Removed i param and update u param

diff --git a/wtf b/wtf
--- a/wtf
+++ b/wtf
@@ -10,7 +10,6 @@
 #%
 #% OPTIONS
 #%    -h,          Print script help
-#%    -i,          Install help files
 #%    -t,          Run script in Dev mode (use files from current directory)
 #%    -u,          Update help files
 #%    -v,          Print script information
@@ -59,20 +58,48 @@ scriptinfo() {
 }
  
 # --- Option processing --------------------------------------------------------
-install() {
-  echo "Clone Git repository to ~/.local/wtf"
-  git clone https://github.com/TheAxelander/wtf.git ~/.local/wtf
+command_exists() {
+  command -v "$@" >/dev/null 2>&1
+}
 
+user_can_sudo() {
+  # Check if sudo is installed
+  command_exists sudo || return 1
+  # The following command has 3 parts:
+  #
+  # 1. Run `sudo` with `-v`. Does the following:
+  #    • with privilege: asks for a password immediately.
+  #    • without privilege: exits with error code 1 and prints the message:
+  #      Sorry, user <username> may not run sudo on <hostname>
+  #
+  # 2. Pass `-n` to `sudo` to tell it to not ask for a password. If the
+  #    password is not required, the command will finish with exit code 0.
+  #    If one is required, sudo will exit with error code 1 and print the
+  #    message:
+  #    sudo: a password is required
+  #
+  # 3. Check for the words "may not run sudo" in the output to really tell
+  #    whether the user has privileges or not. For that we have to make sure
+  #    to run `sudo` in the default locale (with `LANG=`) so that the message
+  #    stays consistent regardless of the user's locale.
+  #
+  ! LANG= sudo -n -v 2>&1 | grep -q "may not run sudo"
+}
+
+sync_script_file() {
   echo "Sync wtf script to /usr/local/bin"
-  sudo rsync -a ~/.local/wtf/wtf /usr/local/bin/wtf
+  if user_can_sudo; then
+    sudo rsync -a ~/.local/wtf/wtf /usr/local/bin/wtf
+  else
+    rsync -a ~/.local/wtf/wtf /usr/local/bin/wtf
+  fi
 }
 
 update() {
   echo "Update Git repository in ~/.local/wtf"
   git -C ~/.local/wtf pull 
 
-  echo "Sync wtf script to /usr/local/bin"
-  sudo rsync -a ~/.local/wtf/wtf /usr/local/bin/wtf
+  sync_script_file
 }
 
 if [[ $# == 0 ]] ; then
@@ -80,7 +107,7 @@ if [[ $# == 0 ]] ; then
     exit 1;
 fi
 
-while getopts ":vhitu" optname
+while getopts ":vhtu" optname
   do
     case "$optname" in
       "v")
@@ -89,10 +116,6 @@ while getopts ":vhitu" optname
         ;;
       "h")
         usagefull
-        exit 0;
-        ;;
-      "i")
-        install
         exit 0;
         ;;
       "t")
